import { GetHousesInput, GetHousesOutput } from "../../lib/types/cases/get-houses";
import { House } from "../../lib/types/house.types";

export const getHousesAction = async (input: GetHousesInput): Promise<GetHousesOutput> => {
    const dummyHouses: House[] = [
        {
            id: "1",
            created_at: new Date(),
            chat_id: "chat1",
            user_id: "user1",
            address: "123 Main St",
            city: "Anytown",
            latitude: 40.7128,
            longitude: -74.0060,
            security_score: 8.5,
            investment_score: 7.2,
            infracstrucute_score: 6.8,
            around_price_estimated: 250000,
            mts_estimated: 120,
            humidity_score: 5.5,
            recent_seismic_events: false,
            ceiling_score: "good",
            floor_score: "excellent",
            finishes_score: "modern",
            bethrooms: 3,
            other_spaces: "garage, garden",
            facade_score: 8.0,
            plugs_score: 7.5,
            special_structures: "solar panels",
            stratum: 3,
        },
        {
            id: "2",
            created_at: new Date(),
            chat_id: "chat2",
            user_id: "user2",
            address: "456 Oak Avenue",
            city: "Springfield",
            latitude: 41.8781,
            longitude: -87.6298,
            security_score: 7.8,
            investment_score: 8.1,
            infracstrucute_score: 7.5,
            around_price_estimated: 320000,
            mts_estimated: 150,
            humidity_score: 4.2,
            recent_seismic_events: true,
            ceiling_score: "excellent",
            floor_score: "good",
            finishes_score: "luxury",
            bethrooms: 4,
            other_spaces: "pool, terrace, garage",
            facade_score: 9.2,
            plugs_score: 8.8,
            special_structures: "smart home system",
            stratum: 4,
        },
        {
            id: "3",
            created_at: new Date(),
            chat_id: "chat3",
            user_id: "user3",
            address: "789 Pine Street",
            city: "Riverside",
            latitude: 33.9533,
            longitude: -117.3962,
            security_score: 6.5,
            investment_score: 6.8,
            infracstrucute_score: 5.9,
            around_price_estimated: 180000,
            mts_estimated: 95,
            humidity_score: 7.1,
            recent_seismic_events: false,
            ceiling_score: "fair",
            floor_score: "good",
            finishes_score: "standard",
            bethrooms: 2,
            other_spaces: "small garden",
            facade_score: 6.5,
            plugs_score: 6.0,
            special_structures: "none",
            stratum: 2,
        },
        {
            id: "4",
            created_at: new Date(),
            chat_id: "chat4",
            user_id: "user4",
            address: "321 Elm Boulevard",
            city: "Fairview",
            latitude: 34.0522,
            longitude: -118.2437,
            security_score: 9.1,
            investment_score: 8.7,
            infracstrucute_score: 8.9,
            around_price_estimated: 450000,
            mts_estimated: 180,
            humidity_score: 3.8,
            recent_seismic_events: false,
            ceiling_score: "excellent",
            floor_score: "excellent",
            finishes_score: "premium",
            bethrooms: 5,
            other_spaces: "wine cellar, gym, garage",
            facade_score: 9.5,
            plugs_score: 9.2,
            special_structures: "elevator, security system",
            stratum: 5,
        },
    ];
    return {
        data: dummyHouses,
        isOk: true,
    };
};
